<h1>Heart Failure Prediction - AutoML<h1>

In [1]:
!pip install scikit-learn==0.23.2

Requirement already satisfied: scikit-learn==0.23.2 in /Users/hasha/opt/anaconda3/lib/python3.8/site-packages (0.23.2)
Requirement already satisfied: scipy>=0.19.1 in /Users/hasha/opt/anaconda3/lib/python3.8/site-packages (from scikit-learn==0.23.2) (1.5.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/hasha/opt/anaconda3/lib/python3.8/site-packages (from scikit-learn==0.23.2) (2.1.0)
Requirement already satisfied: numpy>=1.13.3 in /Users/hasha/opt/anaconda3/lib/python3.8/site-packages (from scikit-learn==0.23.2) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /Users/hasha/opt/anaconda3/lib/python3.8/site-packages (from scikit-learn==0.23.2) (1.0.1)

In [3]:
import sklearn
print(sklearn.__version__)

0.23.2

In [4]:
# Reading the data set
import pandas as pd
df = pd.read_csv('heart.csv')

In [5]:
df.head(2).style.set_properties(**{"background-color": "black","color": "white", "border-color": "black","font-size":"10pt",'width': 200})

In [6]:
from pycaret.classification import *

In [7]:
'''setup()-function initializes the environment in pycaret and creates the transformation pipeline 
to prepare the data for modeling and deployment.'''
s = setup(data = df, target = 'HeartDisease', session_id=123,
 numeric_imputation = 'mean',
             silent = True,
            remove_outliers = True,
            normalize = True)

In [13]:
#Compare with all the classification models
'''Compare_model()-It is a function that actually allows to you create a model is unimaginatively called create_model(). 
This function creates a model and scores it using stratified cross validation'''
best_model = compare_models(round = 4)

In [14]:
print(best_model)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=123, verbose=0,
                       warm_start=False)

In [15]:
# check all the available models
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [19]:
rf = create_model("rf",fold = 5, round = 4)

In [20]:
tuned_rf = tune_model(rf, optimize = 'AUC',round = 4)

In [21]:
plot_model(tuned_rf, plot = 'parameter')

                                  Parameters
bootstrap                               True
ccp_alpha                                0.0
class_weight              balanced_subsample
criterion                            entropy
max_depth                                  4
max_features                            log2
max_leaf_nodes                          None
max_samples                             None
min_impurity_decrease                 0.0002
min_impurity_split                      None
min_samples_leaf                           5
min_samples_split                          9
min_weight_fraction_leaf                 0.0
n_estimators                             130
n_jobs                                    -1
oob_score                              False
random_state                             123
verbose                                    0
warm_start                             False

In [22]:
evaluate_model(tuned_rf)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [23]:
predict_model(tuned_rf)

,Age,RestingBP,Cholesterol,MaxHR,Oldpeak,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,...,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up,HeartDisease,Label,Score
0,-1.830509,-1.268915,-1.773372,-0.490732,0.095737,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1,1,0.9027
1,-1.194126,-0.129872,-0.153288,0.494292,-0.834112,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9229
2,0.078639,-1.268915,0.098725,0.179084,-0.834112,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9492
3,1.669596,0.439649,-0.783321,-1.121148,0.560661,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1,1,0.9470
4,-1.406254,0.439649,0.341737,1.991529,-0.834112,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,0.608958,-0.129872,-0.639313,-0.490732,-0.834112,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,1,0.7943
272,0.290767,-0.699394,-1.773372,0.415490,-0.834112,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1,1,0.7716
273,-1.618381,-0.699394,0.701756,-0.333129,-0.834112,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9536
274,-1.512317,-0.129872,0.161728,-0.687737,-0.834112,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9510
275,0.396830,0.439649,0.152728,0.257886,1.025585,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1,1,0.8397

In [24]:
''' The finalize_model() function fits the model onto the complete dataset including the 
test/hold-out sample (30% in this case). '''
final_rf= finalize_model(tuned_rf)

In [25]:
print(final_rf)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight='balanced_subsample', criterion='entropy',
                       max_depth=4, max_features='log2', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0002,
                       min_impurity_split=None, min_samples_leaf=5,
                       min_samples_split=9, min_weight_fraction_leaf=0.0,
                       n_estimators=130, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)

In [26]:
predict_model(final_rf)

,Age,RestingBP,Cholesterol,MaxHR,Oldpeak,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,...,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up,HeartDisease,Label,Score
0,-1.830509,-1.268915,-1.773372,-0.490732,0.095737,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1,1,0.9135
1,-1.194126,-0.129872,-0.153288,0.494292,-0.834112,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9339
2,0.078639,-1.268915,0.098725,0.179084,-0.834112,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9523
3,1.669596,0.439649,-0.783321,-1.121148,0.560661,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1,1,0.9271
4,-1.406254,0.439649,0.341737,1.991529,-0.834112,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,0.608958,-0.129872,-0.639313,-0.490732,-0.834112,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,1,0.8091
272,0.290767,-0.699394,-1.773372,0.415490,-0.834112,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1,1,0.7853
273,-1.618381,-0.699394,0.701756,-0.333129,-0.834112,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9633
274,-1.512317,-0.129872,0.161728,-0.687737,-0.834112,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0.9431
275,0.396830,0.439649,0.152728,0.257886,1.025585,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1,1,0.8755

In [28]:
'''Save_model() allows you to save the model along with entire transformation pipeline for later use.'''
save_model(final_rf,'Final RF Model 24NOV2021')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=False, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[],
                                       target='HeartDisease',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeri...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight='balanced_subsample',
                                         criterion='entropy', max_depth=4,
                                         max_features='log2',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0002,
                                         min_impurity_split=None,
                                         min_samples_leaf=5, min_samples_split=9,
                                         min_weight_fraction_leaf=0.0,
                                         n_estimators=130, n_jobs=-1,
                                         oob_score=False, random_state=123,
                                         verbose=0, warm_start=False)]],
          verbose=False),
 'Final RF Model 24NOV2021.pkl')